import { defineConfig } from 'oxlint'

const antiSlopRules = {
  'anti-slop/no-chained-type-assertions': 'error',
  'anti-slop/no-conditional-empty-object-spread': 'error',
  'anti-slop/no-known-value-widening': 'error',
  'anti-slop/no-module-mocking': 'error',
  'anti-slop/no-object-parameters': 'error',
  'anti-slop/no-reflect-apply': 'error',
  'anti-slop/no-reflect-get': 'error',
  'anti-slop/no-runtime-typeof': 'error',
  'anti-slop/no-shape-in-symbol-names': 'error',
  'anti-slop/no-unknown-parameters': 'error',
  'anti-slop/no-unknown-returns': 'error',
  'anti-slop/no-unknown-type-aliases': 'error',
  'anti-slop/no-unsafe-dictionary-type': 'error',
  'anti-slop/no-widen-then-assert': 'error',
  'anti-slop/require-safety-comment-for-type-assertion': 'error',
} as const

export default defineConfig({
  ignorePatterns: [
    '.agent/**',
    '.agents/**',
    '.claude/**',
    '.codex/**',
    '.codegraph/**',
    '.continue/**',
    '.cursor/**',
    '.firecrawl/**',
    '.gemini/**',
    '.humanlayer/**',
    '.omc/**',
    '.opencode/**',
    '.pi/**',
    '.roo/**',
    '.scratch/**',
    '.windsurf/**',
    '**/.expo/**',
    '**/.turbo/**',
    '**/android/**',
    '**/build/**',
    '**/coverage/**',
    '**/ios/**',
    '**/scripts/**',
    'tools/oxlint/anti-slop/**',
    '**/*.config.js',
    '**/*.config.cjs',
    '**/*.config.mjs',
    '**/*.config.ts',
  ],
  jsPlugins: [{ name: 'anti-slop', specifier: './tools/oxlint/anti-slop/index.ts' }],
  categories: {
    correctness: 'off',
  },
  rules: {
    ...antiSlopRules,
  },
})
