import { palette } from './palette'

const light = {
  background: palette.white,
  foreground: palette.gray50,
  card: palette.gray2,
  cardForeground: palette.gray50,
  popover: palette.white,
  popoverForeground: palette.gray50,
  primary: palette.gray50,
  primaryForeground: palette.white,
  secondary: palette.warmNeutral,
  secondaryForeground: palette.gray50,
  muted: palette.gray5,
  mutedForeground: palette.gray30,
  accent: palette.gray5,
  accentForeground: palette.gray50,
  destructive: palette.red,
  destructiveForeground: palette.white,
  border: palette.gray15,
  input: palette.gray5,
  ring: palette.blue30,
  chart1: palette.blue30,
  chart2: palette.green30,
  chart3: palette.purple30,
  chart4: palette.orange30,
  chart5: palette.magenta30,
  sidebar: palette.gray2,
  sidebarForeground: palette.gray50,
  sidebarPrimary: palette.teal30,
  sidebarPrimaryForeground: palette.white,
  sidebarAccent: palette.gray5,
  sidebarAccentForeground: palette.gray50,
  sidebarBorder: palette.gray15,
  sidebarRing: palette.blue30,
}

export type SemanticColors = { [Key in keyof typeof light]: string }

const dark: SemanticColors = {
  background: palette.gray50,
  foreground: palette.white,
  card: palette.gray45,
  cardForeground: palette.white,
  popover: palette.gray48,
  popoverForeground: palette.white,
  primary: palette.redDarkMode,
  primaryForeground: palette.white,
  secondary: palette.warmNeutralDm,
  secondaryForeground: palette.white,
  muted: palette.gray40,
  mutedForeground: palette.gray10,
  accent: palette.gray30,
  accentForeground: palette.gray2,
  destructive: palette.red,
  destructiveForeground: palette.white,
  border: palette.gray35,
  input: palette.gray40,
  ring: palette.blue30Dm,
  chart1: palette.blue30Dm,
  chart2: palette.green30Dm,
  chart3: palette.purple30Dm,
  chart4: palette.orange30Dm,
  chart5: palette.magenta30Dm,
  sidebar: palette.gray48,
  sidebarForeground: palette.white,
  sidebarPrimary: palette.teal30Dm,
  sidebarPrimaryForeground: palette.white,
  sidebarAccent: palette.gray40,
  sidebarAccentForeground: palette.white,
  sidebarBorder: palette.gray35,
  sidebarRing: palette.blue30Dm,
}

export const semanticColors = { light, dark }

